# Generated by Django 4.2.11 on 2024-03-25 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rejectCandidateJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hr.candidateapplications')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.jobpost')),
            ],
        ),
    ]
